apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw-admin
  namespace: creatworx
  labels:
    app: cw-admin
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cw-admin
  template:
    metadata:
      labels:
        app: cw-admin
        component: frontend
    spec:
      containers:
      - name: cw-admin
        image: gcr.io/createworx/cw-admin:IMAGE_TAG
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NODE_ENV
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NEXT_PUBLIC_API_URL
        - name: NEXT_PUBLIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NEXT_PUBLIC_APP_NAME
        - name: NEXT_PUBLIC_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NEXT_PUBLIC_APP_VERSION
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cw-admin-secret
              key: JWT_SECRET
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cw-admin-secret
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cw-admin-secret
              key: REDIS_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: gcr-secret
      restartPolicy: Always
