apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw-admin
  namespace: cw-admin
  labels:
    app: cw-admin
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cw-admin
  template:
    metadata:
      labels:
        app: cw-admin
        component: frontend
    spec:
      containers:
      - name: cw-admin
        image: us-central1-docker.pkg.dev/createworx/cw-admin/cw-admin:IMAGE_TAG
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NODE_ENV
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NEXT_PUBLIC_API_URL
        - name: NEXT_PUBLIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NEXT_PUBLIC_APP_NAME
        - name: NEXT_PUBLIC_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: cw-admin-config
              key: NEXT_PUBLIC_APP_VERSION
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      # Add tolerations for node taints
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "production"
        effect: "NoSchedule"
      # Add node selector to prefer production nodes
      nodeSelector:
        dedicated: "production"
      restartPolicy: Always
